name: ${project.name}
author: khmDEV
main: ${project.groupId}.${project.artifactId}.init
version: ${project.version}
commands:
   amigos:
      permission: amigos.command
      permission-message: No tienes permisos <permission>
permissions:
         amigos.command:
                 default: op         
         amigos.tp:
                 default: op
softdepend: [APIAuxiliar,HUB]
Depend: [APIAuxiliar]